version: '3'

services:
    api:
        image: python:latest
        build: .
        ports:
            - "5000:5000"
        volumes:
           - ${proj_path}:/root/VMFarm
        working_dir: /root/VMFarm
